import type { ResponsiveStyleProps } from "../responsiveStyleProps.types";

const STYLE_PROP_KEYS = new Set<string>([
  "display",
  "visibility",
  "overflow",
  "overflowX",
  "overflowY",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexWrap",
  "flexGrow",
  "flexShrink",
  "justifyContent",
  "alignItems",
  "alignContent",
  "alignSelf",
  "order",
  "gap",
  "rowGap",
  "columnGap",
  "spacing",
  "grid",
  "gridArea",
  "gridAutoFlow",
  "gridAutoRows",
  "gridAutoColumns",
  "gridTemplate",
  "gridTemplateAreas",
  "gridTemplateRows",
  "gridTemplateColumns",
  "gridRow",
  "gridRowStart",
  "gridRowEnd",
  "gridColumn",
  "gridColumnStart",
  "gridColumnEnd",
  "placeItems",
  "placeContent",
  "placeSelf",
  "justifyItems",
  "justifySelf",
  "margin",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "marginInline",
  "marginInlineStart",
  "marginInlineEnd",
  "marginBlock",
  "marginBlockStart",
  "marginBlockEnd",
  "marginX",
  "marginY",
  "padding",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
  "paddingInline",
  "paddingInlineStart",
  "paddingInlineEnd",
  "paddingBlock",
  "paddingBlockStart",
  "paddingBlockEnd",
  "paddingX",
  "paddingY",
  "width",
  "minWidth",
  "maxWidth",
  "maxInlineSize",
  "height",
  "minHeight",
  "maxHeight",
  "aspectRatio",
  "boxSizing",
  "position",
  "top",
  "right",
  "bottom",
  "left",
  "inset",
  "insetBlock",
  "insetBlockStart",
  "insetBlockEnd",
  "insetInline",
  "insetInlineStart",
  "insetInlineEnd",
  "insetX",
  "insetY",
  "zIndex",
  "font",
  "fontFamily",
  "fontSize",
  "fontWeight",
  "fontStyle",
  "lineHeight",
  "letterSpacing",
  "textAlign",
  "textTransform",
  "textDecoration",
  "textWrap",
  "whiteSpace",
  "wordBreak",
  "wordWrap",
  "overflowWrap",
  "color",
  "background",
  "backgroundColor",
  "backgroundImage",
  "backgroundSize",
  "backgroundPosition",
  "backgroundRepeat",
  "backgroundClip",
  "opacity",
  "border",
  "borderTop",
  "borderRight",
  "borderBottom",
  "borderLeft",
  "borderColor",
  "borderStyle",
  "borderWidth",
  "borderRadius",
  "outline",
  "outlineColor",
  "outlineStyle",
  "outlineWidth",
  "boxShadow",
]);

type SplitResolvedProps<T extends object> = {
  rest: Omit<T, keyof ResponsiveStyleProps>;
  stylesProps: Partial<ResponsiveStyleProps>;
};

export function resolveProps<T extends object>(props: T): SplitResolvedProps<T> {
  const stylesProps: Partial<ResponsiveStyleProps> = {};
  const rest: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(props)) {
    if (STYLE_PROP_KEYS.has(key)) {
      (stylesProps as Record<string, unknown>)[key] = value;
      continue;
    }

    rest[key] = value;
  }

  return {
    stylesProps,
    rest: rest as Omit<T, keyof ResponsiveStyleProps>,
  };
}
