/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/packages/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List packages
         * @description List packages with pagination and sorting.
         */
        get: operations["listPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search packages
         * @description Searches npm package names using prefix matching and returns the complete package documents.
         */
        get: operations["searchPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "packagesApi.AffectedPackage": {
            ecosystem?: string;
            fixed_version?: string;
            introduced_version?: string;
            last_affected_version?: string;
        };
        "packagesApi.ListResponse": {
            documents?: components["schemas"]["packagesApi.PackageListDocument"][];
            lastPage?: number;
            message?: string;
            status?: number;
            totalPages?: number;
        };
        "packagesApi.PackageCurrentStatus": {
            affected?: components["schemas"]["packagesApi.AffectedPackage"][];
            code?: string;
            cve_id?: string;
            fixed_versions?: string[];
            label?: string;
            osv_id?: string;
            severity?: string;
        };
        "packagesApi.PackageListDocument": {
            current_statuses?: components["schemas"]["packagesApi.PackageCurrentStatus"][];
            ecosystem?: string;
            id?: number;
            is_deprecated?: boolean;
            name?: string;
            popularity?: number;
            slug?: string;
            vulnerabilities?: {
                [key: string]: components["schemas"]["packagesApi.Vulnerability"][];
            };
            vulnerability_counts?: {
                [key: string]: number;
            };
        };
        "packagesApi.SearchDocument": {
            /**
             * @description Package ecosystem.
             * @enum {string}
             */
            ecosystem: "npm";
            /** @description Database package identifier. */
            id: string;
            /** @description Whether npm marks the package as deprecated. */
            is_deprecated: boolean;
            /** @description npm package name. */
            name: string;
            /** @description Download popularity score. */
            popularity: number;
            /** @description URL-safe package identifier. */
            slug: string;
            /** @description Monthly vulnerability counts keyed by YYYY-MM. */
            vulnerabilities: {
                [key: string]: number;
            };
        };
        "packagesApi.SearchResponse": {
            documents?: components["schemas"]["packagesApi.SearchDocument"][];
            message?: string;
            status?: number;
        };
        "packagesApi.Vulnerability": {
            affected?: components["schemas"]["packagesApi.AffectedPackage"][];
            cve_id?: string;
            cvss_score?: number;
            cvss_vector?: string;
            description?: string;
            id?: number;
            modified_at?: string;
            osv_id?: string;
            published_at?: string;
            references?: string[];
            severity?: string;
            summary?: string;
            withdrawn_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPackages: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Maximum number of results */
                limit?: number;
                /** @description Field to sort by (e.g., name, popularity or ecosystem) */
                sortBy?: string;
                /** @description Sort order (asc or desc) */
                order?: string;
                /** @description Package ecosystem */
                ecosystem?: string;
                /** @description Include full vulnerability details */
                includeVulnerabilities?: boolean;
                /** @description Only return packages with vulnerabilities */
                onlyWithVulnerabilities?: boolean;
                /** @description Limit vulnerabilities to the last N months (0 for all available months, 1-12 for a window) */
                vulnerabilityMonths?: number;
                /** @description Include current vulnerability status details */
                withCurrentStatus?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.ListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.ListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.ListResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.ListResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.ListResponse"];
                };
            };
        };
    };
    searchPackages: {
        parameters: {
            query: {
                /** @description Package name or scoped package name */
                query: string;
                /** @description Maximum number of results */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.SearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.SearchResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.SearchResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.SearchResponse"];
                };
            };
        };
    };
}
