/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/packages/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search packages
         * @description Searches npm package names using prefix matching and returns the complete package documents.
         */
        get: operations["searchPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "packagesApi.SearchDocument": {
            /**
             * @description Package ecosystem.
             * @enum {string}
             */
            ecosystem: "npm";
            /** @description Database package identifier. */
            id: string;
            /** @description Whether npm marks the package as deprecated. */
            is_deprecated: boolean;
            /** @description npm package name. */
            name: string;
            /** @description Download popularity score. */
            popularity: number;
            /** @description Monthly vulnerability counts keyed by YYYY-MM. */
            vulnerabilities: {
                [key: string]: number;
            };
        };
        "packagesApi.SearchResponse": {
            documents?: components["schemas"]["packagesApi.SearchDocument"][];
            message: string;
            /** @enum {integer} */
            status: 200 | 400 | 429 | 500;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchPackages: {
        parameters: {
            query: {
                /** @description Package name or scoped package name */
                query: string;
                /** @description Maximum number of results */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.SearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.SearchResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.SearchResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["packagesApi.SearchResponse"];
                };
            };
        };
    };
}
