name: workflow
on:
  pull_request:
jobs:
  code-checks:
    uses: ./.github/workflows/code-checks.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: code-checks

  vulnerabilities-audit:
    uses: ./.github/workflows/vulnerabilities.yml
    needs: code-checks

  security:
    uses: ./.github/workflows/sercurity.yml
    permissions:
      contents: read
      security-events: write
