name: code checks
on:
  workflow_call:
jobs:
  code-checks:
    runs-on: ubuntu-26.04
    steps:
      - name: gather repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.17.0

      - name: Install project dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: typecheck
        shell: bash
        run: pnpm typecheck
