name: vulnerabilities audit
on:
  workflow_call:
jobs:
  vulnerabilities-audit:
    runs-on: ubuntu-26.04
    steps:
      - name: gather repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.17.0

      - name: audit vulnerabilities
        shell: bash
        run: pnpm audit
